class StringManager:

    MSG_INITIATE = "Please define movie title and seating map in [Title] [Row] [SeatsPerRow] format:"
    MSG_WELCOME = "Welcome to GIC Cinemas"
    OPTION_ONE = "[1] Book tickets for {0} ({1} seats available)"
    OPTION_TWO = "[2] Check bookings"
    OPTION_THREE = "[3] Exit"
    MSG_INVALID_NUMBER = "Invalid input. Please enter a valid number."
    MSG_RETRY = "Invalid choice. Please Retry!"
    MSG_THANK_YOU = "Thank you for using GIC Cinemas system. Bye!"
    MSG_RESERVED = "Successfully reserved {0} {1} tickets."
    BOOKING_ID = "Booking ID: {0}"


    BOOKING_ID_INPUT = "Enter booking ID or enter blank to go back to main menu:"
    CONFIRMED_TEXT = "confirmed."
    MSG_ACCEPT_OR_BLANK = "Enter blank to accept seat selection, or enter new seating position:"
    MSG_AVAILABLE_SEAT = "Sorry, there are only {0} seats available."
    MSG_BOOKING_FAILED = "Booking failed. Please try again!"
    MSG_INPUT_ARROW = ">"
    MSG_INVALID_BOOKING = "Invalid booking ID. Please try again."
    MSG_INVALID_INPUT_FORMAT = "Invalid input format. Please follow the instruction and try again!"
    MSG_INVALID_SEAT = "Invalid seat input. Please enter a valid seat selection or leave blank to confirm."
    MSG_NO_BOOKING = "No bookings yet."
    MSG_SELECTED_SEAT = "Selected seats:"
    REQUEST_INPUT = "Please enter your selection:"
    RETURN_TO_MENU = "Returning to main menu."
    SCREEN = "SCREEN"
    TICKET_INPUT = "Enter number of tickets to book, or enter blank to go back to main menu:"
